/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kds_Plugin */

#ifndef _Included_org_kds_Plugin
#define _Included_org_kds_Plugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      org_kds_Plugin
 * Method:     init_1driver
 * Signature:  (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_kds_Plugin_init_1driver
  (JNIEnv *, jobject, jstring);

/*
 * Class:      org_kds_Plugin
 * Method:     helloHabr
 * Signature:  ()V
 */
JNIEXPORT void JNICALL Java_org_kds_Plugin_helloHabr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
